# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bba03588611131e0403fa41abf9e84302c179d171d8568e7096227dffb993da67c195f461df3cc17002fa8f2611c7de236cf3ffa4cfb2bf9320e88cc8bdabd4d

test:
  secret_key_base: b73809ed698754d4b414a6c7c97203f9470ac0f6c06d7a2965979ac0625b31812491b3443049d24f92d22d030b0a08ae111a71d0aeb4c5582daa8e85de420285

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
